### ISSUE TITLE
Subnet association not working on first run

### ISSUE THREAD

**Issue by cndaan** [CloudNationHQ/terraform-azure-vnet#24]
On the first run of this module the associations to the NSG and the Route table always fail. Second run after this it works fine.

Associations probably need a depends_on for the subnet to be created first. 

See error below:

![image](https://github.com/CloudNationHQ/terraform-azure-vnet/assets/112694691/bad02e24-4943-4b9f-8b30-700803ccf264)

**Comment by dkooll** [comment]
Verified the dependency order. It was correct. Seems terraform says subnets are created... but in the azure backbone there is a little bit delay..

Experimenting and testing by adding a little bit extra time before attaching the network security groups
